name: Windows Server

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setting Up User
      shell: pwsh
      run: .\user.ps1

    - name: Tunnelling 
      shell: pwsh
      run: .\ngrok.ps1

    - name: Holder
      run: sleep 86400  # 24 hours in seconds
